### ISSUE TITLE
Thảo luận Reinforcement learning

### ISSUE THREAD

**Issue by phamdinhkhanh** [aivivn/Machine-Learning-Yearning-Vietnamese-Translation#504]
![image](https://user-images.githubusercontent.com/24260166/72048948-8437a300-32f0-11ea-9e0c-a8a84da28060.png)

Hiện tại đã có một thuật ngữ được cộng đồng dịch là `học tăng cường`, ám chỉ các thuật toán biến đổi 1 hình ảnh thành nhiều hình ảnh khác bằng các phép rotation, translation, perspective transform,.... Đó chính là `data augumentation`. Còn `Reinforcement learning`  thì được dịch là `Học củng cố`.

Sử dụng thuật ngữ `học củng cố` sẽ phù hợp hơn `học tăng cường` khi dịch `Reinforcement learning` vì thuật toán `Reinforcement learning` sẽ củng cố lại quá trình ra quyết định của mình sau mỗi step để đạt được reward là cao nhất.

**Comment by quangnhat185** [comment]
Cái này phải bàn hết sức cẩn thận. Vì hiện tại từ `học tăng cường` được sử dụng phổ biến hơn `học củng cố` tại các tài liệu ở Việt Nam. Kiểm tra trên google thì `học tăng cường` có gần 90 triệu result còn `học củng cố` chỉ có 14 triệu thôi.

Nếu xét về nghĩa thì trên wiki định nghĩa _Reinforcement learning (RL) is an area of machine learning concerned with how software agents ought to take actions in an environment in order to **maximize** some notion of cumulative reward_. Từ `maximize `ở đây cũng có hiểu như là` tăng cường` vậy

**Comment by ngcthuong** [comment]
> học tăng cường, ám chỉ các thuật toán biến đổi 1 hình ảnh thành nhiều hình ảnh khác bằng các phép rotation, translation, perspective transform,....

ai dịch cái này vậy? Dịch như vậy là sai.

**Comment by phamdinhkhanh** [comment]
> > học tăng cường, ám chỉ các thuật toán biến đổi 1 hình ảnh thành nhiều hình ảnh khác bằng các phép rotation, translation, perspective transform,....
> 
> ai dịch cái này vậy? Dịch như vậy là sai.

Cái này là em nói theo cách hiểu của mình có tham khảo một số giải thích từ các bài viết từ forum nước ngoài chứ ko phải định nghĩa formal dịch từ nguồn nào cả. Ko biết là anh có bổ sung gì thêm ko?
